version: '3.7'
services:
  api:
    container_name: api
    image: movie-db-node-docker/node
    depends_on:
      - database
    networks:
      - app-connect
    ports:
      - '3000:3000'

  database:
    container_name: database
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-connect

volumes:
  database:

networks:
  app-connect:
    driver: bridge
